import Navbar from "../../components/ui/navigation/Navbar";
import { ReactNode } from "react";

interface ShopLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Venus Store | SHOP",
  description: "Generated by create next app",
};

export default function ShoptLayout({ children }: ShopLayoutProps) {
  return <main className="mx-1 sm:mx-32">{children}</main>;
}
